In [1]:
import pandas as pd
import numpy as np
data=pd.read_csv(r"cervical-cancer_csv.csv")
data.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
2,34,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,...,NaN,NaN,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,...,NaN,NaN,0,0,0,0,0,0,0,0

In [2]:
print(data.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
830    False
831    False
832    False
833    False
834    False
Length: 835, dtype: bool

In [3]:
print(data.isnull().sum())

Age                                     0
Number of sexual partners              25
First sexual intercourse                6
Num of pregnancies                     56
Smokes                                 13
Smokes (years)                         13
Smokes (packs/year)                    13
Hormonal Contraceptives               103
Hormonal Contraceptives (years)       103
IUD                                   112
IUD (years)                           112
STDs                                  100
STDs (number)                         100
STDs:condylomatosis                   100
STDs:cervical condylomatosis          100
STDs:vaginal condylomatosis           100
STDs:vulvo-perineal condylomatosis    100
STDs:syphilis                         100
STDs:pelvic inflammatory disease      100
STDs:genital herpes                   100
STDs:molluscum contagiosum            100
STDs:AIDS                             100
STDs:HIV                              100
STDs:Hepatitis B                      100
STDs:HPV                              100
STDs: Number of diagnosis               0
STDs: Time since first diagnosis      764
STDs: Time since last diagnosis       764
Dx:Cancer                               0
Dx:CIN                                  0
Dx:HPV                                  0
Dx                                      0
Hinselmann                              0
Schiller                                0
Citology                                0
Biopsy                                  0
dtype: int64

In [4]:
data.fillna(0, inplace=True)

In [5]:
print(data.isnull().sum())

Age                                   0
Number of sexual partners             0
First sexual intercourse              0
Num of pregnancies                    0
Smokes                                0
Smokes (years)                        0
Smokes (packs/year)                   0
Hormonal Contraceptives               0
Hormonal Contraceptives (years)       0
IUD                                   0
IUD (years)                           0
STDs                                  0
STDs (number)                         0
STDs:condylomatosis                   0
STDs:cervical condylomatosis          0
STDs:vaginal condylomatosis           0
STDs:vulvo-perineal condylomatosis    0
STDs:syphilis                         0
STDs:pelvic inflammatory disease      0
STDs:genital herpes                   0
STDs:molluscum contagiosum            0
STDs:AIDS                             0
STDs:HIV                              0
STDs:Hepatitis B                      0
STDs:HPV                              0
STDs: Number of diagnosis             0
STDs: Time since first diagnosis      0
STDs: Time since last diagnosis       0
Dx:Cancer                             0
Dx:CIN                                0
Dx:HPV                                0
Dx                                    0
Hinselmann                            0
Schiller                              0
Citology                              0
Biopsy                                0
dtype: int64

In [6]:
print(data.isnull().sum().sum())

0

In [7]:
data

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
2,34,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.00,0.0,...,0.0,0.0,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830,34,3.0,18.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
831,32,2.0,19.0,1.0,0.0,0.0,0.0,1.0,8.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
832,25,2.0,17.0,0.0,0.0,0.0,0.0,1.0,0.08,0.0,...,0.0,0.0,0,0,0,0,0,0,1,0
833,33,2.0,24.0,2.0,0.0,0.0,0.0,1.0,0.08,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
834,29,2.0,20.0,1.0,0.0,0.0,0.0,1.0,0.50,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0

In [8]:
data.head(35)

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
2,34,1.0,0.0,1.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.000000,37.000000,1.0,3.00,0.0,...,0.0,0.0,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.000000,0.000000,1.0,15.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
5,42,3.0,23.0,2.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
6,51,3.0,17.0,6.0,1.0,34.000000,3.400000,0.0,0.00,1.0,...,0.0,0.0,0,0,0,0,1,1,0,1
7,26,1.0,26.0,3.0,0.0,0.000000,0.000000,1.0,2.00,1.0,...,0.0,0.0,0,0,0,0,0,0,0,0
8,45,1.0,20.0,5.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,0.0,0.0,1,0,1,1,0,0,0,0
9,44,3.0,15.0,0.0,1.0,1.266973,2.800000,0.0,0.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
10,44,3.0,26.0,4.0,0.0,0.000000,0.000000,1.0,2.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
11,27,1.0,17.0,3.0,0.0,0.000000,0.000000,1.0,8.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
12,45,4.0,14.0,6.0,0.0,0.000000,0.000000,1.0,10.00,1.0,...,0.0,0.0,0,0,0,0,0,0,0,0
13,44,2.0,25.0,2.0,0.0,0.000000,0.000000,1.0,5.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
14,43,2.0,18.0,5.0,0.0,0.000000,0.000000,0.0,0.00,1.0,...,0.0,0.0,0,0,0,0,0,0,0,0
15,40,3.0,18.0,2.0,0.0,0.000000,0.000000,1.0,15.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
16,41,4.0,21.0,3.0,0.0,0.000000,0.000000,1.0,0.25,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
17,43,3.0,15.0,8.0,0.0,0.000000,0.000000,1.0,3.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
18,42,2.0,20.0,0.0,0.0,0.000000,0.000000,1.0,7.00,1.0,...,0.0,0.0,0,0,0,0,0,0,0,0
19,40,2.0,27.0,0.0,0.0,0.000000,0.000000,0.0,0.00,1.0,...,0.0,0.0,0,0,0,0,0,0,0,0
20,43,2.0,18.0,4.0,0.0,0.000000,0.000000,1.0,15.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
21,41,3.0,17.0,4.0,0.0,0.000000,0.000000,1.0,10.00,0.0,...,21.0,21.0,0,0,0,0,0,0,0,0
22,40,1.0,18.0,1.0,0.0,0.000000,0.000000,1.0,0.25,0.0,...,2.0,2.0,0,0,0,0,0,1,1,1
23,40,1.0,20.0,2.0,0.0,0.000000,0.000000,1.0,15.00,0.0,...,0.0,0.0,1,0,1,0,1,1,0,1
24,40,3.0,15.0,3.0,0.0,0.000000,0.000000,1.0,3.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
25,44,3.0,19.0,1.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
26,39,5.0,23.0,2.0,0.0,0.000000,0.000000,0.0,0.00,1.0,...,0.0,0.0,0,0,0,0,0,0,0,0
27,39,2.0,17.0,4.0,0.0,0.000000,0.000000,0.0,0.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
28,37,3.0,24.0,1.0,1.0,3.000000,0.040000,0.0,0.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
29,37,6.0,26.0,1.0,0.0,0.000000,0.000000,1.0,0.25,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
30,41,3.0,17.0,3.0,0.0,0.000000,0.000000,1.0,22.00,1.0,...,0.0,0.0,0,0,0,0,0,0,0,0
31,40,2.0,21.0,2.0,0.0,0.000000,0.000000,1.0,19.00,1.0,...,0.0,0.0,0,0,0,0,0,0,0,0
32,37,3.0,17.0,5.0,1.0,1.266973,0.513202,1.0,10.00,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
33,37,3.0,15.0,3.0,0.0,0.000000,0.000000,1.0,0.50,1.0,...,0.0,0.0,0,0,0,0,0,0,0,0
34,38,2.0,15.0,2.0,0.0,0.000000,0.000000,1.0,0.50,1.0,...,0.0,0.0,0,0,0,0,0,1,0,0

In [9]:
data.drop(
    columns=[
        'STDs: Time since first diagnosis',
        'STDs: Time since last diagnosis'
    ],
    inplace=True
)

# Remove the index column if it exists
data.drop(columns=['Unnamed: 0'], errors='ignore', inplace=True)

In [10]:
data

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs:HPV,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
2,34,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.00,0.0,...,0.0,0,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830,34,3.0,18.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
831,32,2.0,19.0,1.0,0.0,0.0,0.0,1.0,8.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
832,25,2.0,17.0,0.0,0.0,0.0,0.0,1.0,0.08,0.0,...,0.0,0,0,0,0,0,0,0,1,0
833,33,2.0,24.0,2.0,0.0,0.0,0.0,1.0,0.08,0.0,...,0.0,0,0,0,0,0,0,0,0,0
834,29,2.0,20.0,1.0,0.0,0.0,0.0,1.0,0.50,0.0,...,0.0,0,0,0,0,0,0,0,0,0

In [11]:
print(data.isnull().sum())

Age                                   0
Number of sexual partners             0
First sexual intercourse              0
Num of pregnancies                    0
Smokes                                0
Smokes (years)                        0
Smokes (packs/year)                   0
Hormonal Contraceptives               0
Hormonal Contraceptives (years)       0
IUD                                   0
IUD (years)                           0
STDs                                  0
STDs (number)                         0
STDs:condylomatosis                   0
STDs:cervical condylomatosis          0
STDs:vaginal condylomatosis           0
STDs:vulvo-perineal condylomatosis    0
STDs:syphilis                         0
STDs:pelvic inflammatory disease      0
STDs:genital herpes                   0
STDs:molluscum contagiosum            0
STDs:AIDS                             0
STDs:HIV                              0
STDs:Hepatitis B                      0
STDs:HPV                              0
STDs: Number of diagnosis             0
Dx:Cancer                             0
Dx:CIN                                0
Dx:HPV                                0
Dx                                    0
Hinselmann                            0
Schiller                              0
Citology                              0
Biopsy                                0
dtype: int64

In [12]:
print(data.dtypes)

Age                                     int64
Number of sexual partners             float64
First sexual intercourse              float64
Num of pregnancies                    float64
Smokes                                float64
Smokes (years)                        float64
Smokes (packs/year)                   float64
Hormonal Contraceptives               float64
Hormonal Contraceptives (years)       float64
IUD                                   float64
IUD (years)                           float64
STDs                                  float64
STDs (number)                         float64
STDs:condylomatosis                   float64
STDs:cervical condylomatosis          float64
STDs:vaginal condylomatosis           float64
STDs:vulvo-perineal condylomatosis    float64
STDs:syphilis                         float64
STDs:pelvic inflammatory disease      float64
STDs:genital herpes                   float64
STDs:molluscum contagiosum            float64
STDs:AIDS                             float64
STDs:HIV                              float64
STDs:Hepatitis B                      float64
STDs:HPV                              float64
STDs: Number of diagnosis               int64
Dx:Cancer                               int64
Dx:CIN                                  int64
Dx:HPV                                  int64
Dx                                      int64
Hinselmann                              int64
Schiller                                int64
Citology                                int64
Biopsy                                  int64
dtype: object

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [14]:
X = data.drop(columns=['Biopsy'])
y = data['Biopsy']

In [15]:
data

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs:HPV,STDs: Number of diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
2,34,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.00,0.0,...,0.0,0,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
830,34,3.0,18.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
831,32,2.0,19.0,1.0,0.0,0.0,0.0,1.0,8.00,0.0,...,0.0,0,0,0,0,0,0,0,0,0
832,25,2.0,17.0,0.0,0.0,0.0,0.0,1.0,0.08,0.0,...,0.0,0,0,0,0,0,0,0,1,0
833,33,2.0,24.0,2.0,0.0,0.0,0.0,1.0,0.08,0.0,...,0.0,0,0,0,0,0,0,0,0,0
834,29,2.0,20.0,1.0,0.0,0.0,0.0,1.0,0.50,0.0,...,0.0,0,0,0,0,0,0,0,0,0

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2,
    stratify=y, random_state=42
)

In [17]:

model = make_pipeline(
    SimpleImputer(strategy='median'),
    StandardScaler(),
    LogisticRegression(
        class_weight='balanced',
        max_iter=1000
    )
)

In [18]:
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [19]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.97      0.98       156
           1       0.71      0.91      0.80        11

    accuracy                           0.97       167
   macro avg       0.85      0.94      0.89       167
weighted avg       0.98      0.97      0.97       167